### ISSUE TITLE
Replace Rolls

### ISSUE THREAD

**Issue by cidthecoatrack** [DnDGen/RollGen#10]
Add a `ReplaceRolls` method, which will take a string, find any rolls, and replace them with their totals

**Comment by aloisdg** [comment]
Can you give an example of this?

`"foo 1d6 bar"` => `"foo 4 bar"`?

**Comment by cidthecoatrack** [comment]
Certainly:

``` csharp
var description = "Contains 1d6+2 ghouls and 2d4 zombies";
description = dice.ReplaceRolls(description);
//results: "Contains 4 ghouls and 7 zombies"
```

**Comment by aloisdg** [comment]
Awesome feature!

**Comment by cidthecoatrack** [comment]
Can also work like this:

``` csharp
var description = "3d6+4";
description = dice.ReplaceRolls(description);
//results: "19"
```

**Comment by cidthecoatrack** [comment]
@Lirusaito A question for you - given your use, how important is it to have the quantity-less roll?  A.k.a., `d6` = `1d6`.  It is complicating this current feature.  As an example:

``` csharp
[TestCase("Contains 1d6+2 ghouls and 2d4 zombies", "Contains 2 ghouls and 1 zombies")]
public void ReplaceExpressionWithTotals(string expression, string expectedExpression)
{
    mockPartialRoll.Setup(r => r.IndividualRolls(It.IsAny<int>())).Returns((int d) => BuildIndividualRolls(d));

    var count = 1;
    mockExpressionEvaluator.Setup(e => e.Evaluate(It.IsAny<string>())).Returns(() => count++);

    var newExpression = dice.ReplaceRolls(expression);
    Assert.That(newExpression, Is.EqualTo(expectedExpression));
    //instead of "Contains 2 ghouls and 1 zombies", you get "Contains 4 ghouls an23 zombies"
}
```

It's the combination of the spaces and no quantity that makes it awkward.

**Comment by cidthecoatrack** [comment]
If I had to pick losing one feature amongst this new string replacement, being able to ignore spaces around die rolls, and rolling without quantities, I would pick rolling without quantities to go - but again, it depends very much on what your use cases are.

**Comment by Lirusaito** [comment]
What if we could mark up rolls that should be replaced in a special syntax
like

```Contains {1d6+2} ghouls and {2d4} zombies```?

**Comment by LiruMouse** [comment]
What if we could mark up rolls and other expressions that should be replaced in a special syntax
like `Contains {1d6+2} ghouls and {2d4} zombies`?
In fact, that might even simplify your regex because you'd be able to search only for expressions between `{` and `}`, maybe also support `\{` and `\}` and then you could do a `str.Replace("\{", "{");` when done.

**Comment by cidthecoatrack** [comment]
The idea is that it can just be a regular plain-text string - but I think I may have figured out a way to alter to regex to make it work.  I'm going to give it a try and will comment back in here.

**Comment by LiruMouse** [comment]
I mean, if you're going to have it replace something, you might as well have more syntactic sugar to ensure you don't replace the wrong things, right?

**Comment by cidthecoatrack** [comment]
I'm thinking that if we set up the regex correctly, it won't matter.  My tests so far are promising - I'll post the resulting regex here if it works as I expect it will.

**Comment by LiruMouse** [comment]
But if you have something like a username in the string, it could mess it up even if it's right if we keep the nonspecified quantity feature: `Fred2 has 4d16 health.`, right?

**Comment by cidthecoatrack** [comment]
I think the regex will even handle that - I'll put that in as a test case to verify :)

**Comment by cidthecoatrack** [comment]
So this regex (`((\d* +)|(\d+ *)|(^))d *\d+`) works correctly for all these test cases:
- 1d2
- 2d3
- 1+2d3
- 1d2+3
- 1d2+3d4
- 1+2d3-4d6*5
- 1+2d3-4d5*6
- 1+2d3-2d3/4
- 1+2d3-2d3*4/5
- d2
- I want to roll a d2. (The d2 is rolled)
- I want to roll 1 d2. (The d2 is rolled)
- 1+2
- "  1  d     2    " (Trims the spaces off the end)
- one d two
- other things
- Contains 1d6+2 ghouls and 2d4 zombies
- Contains 1d6+2 ghouls, 1d4+1 skeletons, and 2d4 zombies
- Hydra (1d4+4 heads)
- Hydra (10+2 heads)
- 6d6 fire damage
- I hit for 1d4
- I found 5 golden rings, 4 calling birds, 3 french hens, 2 turtle doves, and 1 partridge in a pear tree
- I am 1d100% confident
- Fred2 has 4d16 health.
- Fred2

To see what the "correct" output is, see the automated tests in the commit related to this issue.

I am going to call this feature done and merge it in.

**Comment by LiruMouse** [comment]
As I work on #13 I decided to look at the new dice regex, it appears it will not accept such expressions as `d10+3+d20+1d20`, the only expressions matched in this string will be the first `d10` and last `1d20` . The reason the first one is matched is because of the `^` beginning of string, subsequent quantityless rolls won't be at the beginning of the string, obviously, so they have to be matched some way else.

I could be wrong... it seems like only `d10+ d20` kinda thing will work, where there's a space before a die with quantity omission... that kinda breaks behavior.

**Comment by cidthecoatrack** [comment]
That is a good point.  The regex can be improved there to also look for one of the arithmetic signs.  I will make a separate issue for that defect.  If you want to address it in #13, that is fine, or we can work it in a separate commit.
