### ISSUE TITLE
Is there a verbose mode?

### ISSUE THREAD

**Issue by aloisdg** [DnDGen/RollGen#12]
Hello,

Is it possible to have something like this:

``` C#
Console.WriteLine(dice.Roll("5+3d4*2", isVerbose: true));
```

output: 

```
5 + (1 + 1 + 3)*2
```

where `1`, `1`, and `3` are the value rolled.

---

quick question:

`2d4*2` equals `4d4` or `(2d4)*2`?

**Comment by cidthecoatrack** [comment]
Currently if you use `RollExpression`, it will give you that verbose output.

``` csharp
var expression = dice.RollExpression("5+3d4*2");
// expression = "5+(1 + 1 + 3)*2"
```

If there is a different method name that could make what it is returning clearer, I am all for it. :)

As for your quick question, as you can see from the example above, `2d4*2` is equal to `(2d4)*2`.  This is the common practice for certain rolls such as coins (`1d4*1000` should be 1K, 2K, 3K, or 4K)

**Comment by aloisdg** [comment]
I have not problem with this name. Thank you for your answer.

**Comment by cidthecoatrack** [comment]
The name for this method is (in 11.0) "ReplaceRollsWithSum"
