### ISSUE TITLE
Restructure solution

### ISSUE THREAD

**Issue by cidthecoatrack** [DnDGen/RollGen#14]
Restructure the solution to better match the Nuget deployment packages:
- RollGen - stays the same
- RollGen.Bootstrap - include RollGen.Domain and RollGen.Bootstrap
  - IoC items (such as Ninject) are public
  - RollGen.Domain items become internal to the DLL

**Comment by LiruMouse** [comment]
I was using DomainDice directly and now it's impossible to do so? That's kinda annoying, but I guess I'll live.

**Comment by cidthecoatrack** [comment]
Yeah, I wanted to force people to use the Ninject injection and keep the
concrete implementations hidden.
