### ISSUE TITLE
Support keeping highest of rolls

### ISSUE THREAD

**Issue by LiruMouse** [DnDGen/RollGen#16]
In some dice parsers, there exists a feature to have expressions with k; to explain, here's an example:
`4d5` = `(2 + 4 + 1 + 5) = 12.`
`4d5k3` = `(2 + 4 + 5) = 11.`
`4d5k2` = `(4 + 5) = 9.`
To get these numbers, we could do a `string.Split` on the `" + "` on the substring without the first and last characters (the parentheses).
We'll need to decide if order matters, because we could just do a sort and pull out the lowest...
If we want order, we could do that all the same, but in a duplicate object and then do something like `original = original.Where(n => sorted.Contains(n));`

**Comment by cidthecoatrack** [comment]
A great feature idea.  I do a form of this manually in the CharacterGen project, getting the best 3 of a `4d6` for character stats:

``` csharp
var rolls = dice.Roll(4).IndividualRolls(6);
rolls = rolls.OrderBy(r => r);
var roll = rolls.Skip(1).Sum();
```

I would say order doesn't matter - if someone sees the sum as `(3 + 2 + 4)` or `(2 + 3 + 4)`, it shouldn't be that important.

For where we are using a `k` variable, we could go into the function that is manually parsing the die roll (splitting on `d`) and add a further split on `k` (which would become `sections[2]`.  We would need to add the `k` as part of the die roll regex.  For the code below, obviously there are situations of quantity-less or there is no `k` that we will have to take into account, but this is just a short example.

``` csharp
var sections = rollMatch.Value.Split('d', 'k');
var quantity = Convert.ToInt32(sections[0]);
var die = Convert.ToInt32(sections[1]);
var keep = Convert.ToInt32(sections[2]);

var rolls = dice.Roll(quantity).IndividualRolls(die);
var keptRolls = rolls.OrderByDescending(r => r).Take(keep);
```

This could be very easy to implement.  Great feature idea.
