### ISSUE TITLE
Set limits on numeric inputs for custom dice

### ISSUE THREAD

**Issue by cidthecoatrack** [DnDGen/RollGen#20]
- [x] Cap string roll expression at 10,000d10,000 (as seen in the stress tests)
  - [x] Include cap at 10,000d1
  - [x] Include cap at 1d10,000
- [x] Cap numeric custom rolls (`dice.Roll(x).d(y)`)
  - [x] Figure out what the cap is for here
  - [x] Enforce cap from above

**Comment by cidthecoatrack** [comment]
- [x] Actually, find out what the actual arithmetic cap is between 10K and 100K for expressions, set the cap there.
- [x] Also test to see if multiple max-limit rolls cause a problem.  If so, then maybe a cap isn't worth it

**Comment by cidthecoatrack** [comment]
Cap will be at 46,340

**Comment by LiruMouse** [comment]
Is there a reason we need limits? What if we're deployed to a server that could easily handle them?
Oh, there is an arithmetic cap? Couldn't we try switching to larger types under those conditions?

**Comment by cidthecoatrack** [comment]
The limits are semi-arbitrary, but there are some reasons:

1) the product of the quantity and die must be less than int.MaxValue, or
the Sum() function on individual rolls can cause an arithmetic overflow
2) The quantity must be less than ~10 billion, or the List throws an out of
memory exception (I may have figured out a way around this that I am going
to test)
3) The die itself is really only limited by int.MaxValue

I am going to test something for the quantity, and if it works, then in
theory max value would be the only limit for quantity and die, individually
(the product rule would still apply).
