### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by aloisdg** [DnDGen/RollGen#4]
Hello,

Could you add some documentations about RollGen?
A basic README would be a nice start.
I would love to involve myself in your project in the future.
Glad to find a c# dev who love DnD :)

Cheers,

**Comment by cidthecoatrack** [comment]
Gladly!  So happy to see other's involved in the projects as well!

**Comment by cidthecoatrack** [comment]
@aloisdg - I have updated the README.md on master.  Take a look and tell me if it satisfies your needs. :)

**Comment by aloisdg** [comment]
Nice. What is the license of the project?

**Comment by cidthecoatrack** [comment]
I hadn't decided on a license until you just asked - but MIT is probably appropriate :)  I'll add the license file.

**Comment by cidthecoatrack** [comment]
With the new README (after merging further changes in #5) and the new License file, I'm going to close this issue.

**Comment by aloisdg** [comment]
Ok great.
