### ISSUE TITLE
Explode on specific number

### ISSUE THREAD

**Issue by LiruMouse** [DnDGen/RollGen#43]
`1d4e2`
This expression would explode if we roll a 2
`1d4e2!`
This expression would explode if  we roll a 4
`1d4e2e3!`
This expression would explode if we don't roll a 1.

To add this feature, we should create an array of what to explode on, where ! adds the `Die` to the array. We should change the Explode boolean to the array, and check its emptiness where we use its truth value. `.Explode()` should take a single number or a container of numbers.

What  would we do if everything is in the array?
Tests to make sure we  don't explode if everything is in the array.

**Comment by cidthecoatrack** [comment]
So `1d4e2` and `1d4e2!` are synonymous?  Or is `1d4e2!` an explode on 2 OR 4?  Then `1d4e2e3!` would explode on 2, 3, or 4

**Comment by LiruMouse** [comment]
`1d4e2!` means explode on both 2 and 4

**Comment by LiruMouse** [comment]
! becomes shorthand for explode on max, but you can also say `d4e4` if you want

**Comment by LiruMouse** [comment]
We'll want to use a container type that can only have unique entries.

**Comment by cidthecoatrack** [comment]
HashSet should work fine

**Comment by LiruMouse** [comment]
Would SortedSet be better?

**Comment by cidthecoatrack** [comment]
Maybe - haven't used it much myself.
